local lexers = vis.lexers

local darkbg = '#0D0F14'

local base01 = '#20201d'
local base02 = '#3a3936'
local base03 = '#929185'
local base04 = '#c9c7ba'
local base05 = '#e5e2dd'
local base06 = '#e5e2dd'
local base07 = '#e5e2dd'
local base08 = '#ffb4ab'
local base09 = '#ffffff'
local base0A = '#c9c7b4'
local base0B = '#ffffff'
local base0C = '#e2e5c3'
local base0D = '#ffffff'
local base0E = '#c9c7b4'
local base0F = '#929185'

lexers.STYLE_DEFAULT          = 'back:'..darkbg..',fore:'..base05
lexers.STYLE_NOTHING          = 'back:'..darkbg
lexers.STYLE_CLASS            = 'fore:'..base0A..',bold'
lexers.STYLE_COMMENT          = 'fore:'..base03
lexers.STYLE_CONSTANT         = 'fore:'..base09
lexers.STYLE_DEFINITION       = 'fore:'..base05
lexers.STYLE_ERROR            = 'fore:'..base08
lexers.STYLE_FUNCTION         = 'fore:'..base0D
lexers.STYLE_KEYWORD          = 'fore:'..base0E
lexers.STYLE_LABEL            = 'fore:'..base0C
lexers.STYLE_NUMBER           = 'fore:'..base09
lexers.STYLE_OPERATOR         = 'fore:'..base05
lexers.STYLE_REGEX            = 'fore:'..base0B
lexers.STYLE_STRING           = 'fore:'..base0B
lexers.STYLE_PREPROCESSOR     = 'fore:'..base0F
lexers.STYLE_TAG              = 'fore:'..base08
lexers.STYLE_TYPE             = 'fore:'..base0A..',bold'
lexers.STYLE_VARIABLE         = 'fore:'..base08
lexers.STYLE_WHITESPACE       = ''
lexers.STYLE_EMBEDDED         = 'fore:'..base05
lexers.STYLE_IDENTIFIER       = 'fore:'..base05
lexers.STYLE_LINENUMBER        = 'fore:'..base03
lexers.STYLE_LINENUMBER_CURSOR = 'fore:'..base0D..',bold'
lexers.STYLE_CURSOR           = 'fore:'..darkbg..',back:'..base05
lexers.STYLE_CURSOR_PRIMARY   = lexers.STYLE_CURSOR
lexers.STYLE_CURSOR_LINE      = 'underlined'
lexers.STYLE_COLOR_COLUMN     = 'back:'..base01
lexers.STYLE_SELECTION        = 'fore:'..darkbg..',back:'..base0A
lexers.STYLE_STATUS           = 'back:'..base01..',fore:'..base04
lexers.STYLE_STATUS_FOCUSED   = 'back:'..base04..',fore:'..base01..',bold'
lexers.STYLE_SEPARATOR        = lexers.STYLE_DEFAULT
lexers.STYLE_INFO             = 'fore:default,back:default,bold'
lexers.STYLE_EOF              = ''
