theme[main_fg]="#e6e1ea"

theme[title]="#cabeff"

theme[hi_fg]="#cac1ed"

theme[selected_bg]="#cabeff"

theme[selected_fg]="#321c7e"

theme[inactive_fg]="#c9c4d3"

theme[proc_misc]="#ffaaf8"

theme[cpu_box]="#938f9d"

theme[mem_box]="#938f9d"

theme[net_box]="#938f9d"

theme[proc_box]="#938f9d"

theme[div_line]="#484552"

theme[temp_start]="#cac1ed"
theme[temp_mid]="#cabeff"
theme[temp_end]="#ffb4ab"

theme[cpu_start]="#cac1ed"
theme[cpu_mid]="#cabeff"
theme[cpu_end]="#ffb4ab"

theme[free_start]="#cac1ed"
theme[free_mid]=""
theme[free_end]="#4b4469"

theme[cached_start]="#ffaaf8"
theme[cached_mid]=""
theme[cached_end]="#4b004e"

theme[available_start]="#cabeff"
theme[available_mid]=""
theme[available_end]="#290e75"

theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

theme[download_start]="#cac1ed"
theme[download_mid]="#cabeff"
theme[download_end]="#ffaaf8"

theme[upload_start]="#cac1ed"
theme[upload_mid]="#cabeff"
theme[upload_end]="#ffaaf8"
